name: "Update Changelog"

on:
  release:
    types: [released]

jobs:
  update:
    uses: dymexjs/reusable_workflows/.github/workflows/update-changelog.yml@main
    permissions:
      contents: write
    secrets:
      deploy-key: ${{ secrets.DEPLOY_KEY }}
